name: 'Cbindgen Action'
author: 'Brenno Lemos'
description: 'Automatically generate C/C++ bindings for your Rust code.'
branding:
  icon: "box"
  color: "orange"

inputs:
  github_token:
    description: "A GitHub token for pushing to the repo. Example: https://git.io/passing-token"
    required: true

  config:
    description: "Path of the cbindgen configuration file."
    default: "cbindgen.toml"

  output:
    description: "Path where to save the generated bindings."
    required: true

  toolchain:
    type: choice
    description: "Rust toolchain to be used."
    options:
    - stable
    - nightly
    default: stable

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: "true"

    - name: Use Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}

    - name: Install cbindgen
      uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: cbindgen

    - name: Generate C/C++ bindings
      shell: bash
      run: cbindgen --config=${{ inputs.config }} --output=${{ inputs.output }}

    - name: Commit bindings
      uses: stefanzweifel/git-auto-commit-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        commit_message: Update generated C/C++ Bindings
        branch: ${{ github.ref_name }}
        commit_user_name: cbindgen-action
        commit_user_email: actions@github.com
        commit_author: cbindgen-action <actions@github.com>
        file_pattern: ${{ inputs.output }}
